-- 1. Kokį gyvūną augina Wyatt Johnson? Pateikti gyvūno rūšį, lytį, spalvą, gyvūno vardą.
SELECT S.NAME AS 'SPECIES', G.NAME AS 'GENDER', C.NAME 'COLOUR', AB.NAME
FROM HOST H 
JOIN ANIMAL_BASIC AB ON H.HOST_ID = AB.HOST_ID
JOIN GENDER G ON AB.GENDER_ID = G.GENDER_ID 
JOIN SPECIES S ON AB.SPECIES = S.SPECIES_CODE
JOIN COLOUR C ON S.COLOUR_CODE = C.COLOUR_CODE
WHERE H.NAME = 'Wyatt' 
AND H.SURNAME = 'Johnson';

-- 2. Kokia yra gyvūno Lucy rūšis? Pateikti informaciją apie čipą ir jo gamintoją. 
SELECT AB.NAME, S.NAME AS 'SPECIES', C.MANUFACTURER_CODE, C.NAME AS 'CHIP_NAME', CP.NAME AS 'CHIP_PLACE'
FROM ANIMAL_BASIC AB 
JOIN SPECIES S ON AB.SPECIES = S.SPECIES_CODE
JOIN CHIP C ON AB.CHIP_ID = C.CHIP_ID 
JOIN CHIP_PLACE CP ON C.CHIP_PLACE_CODE = CP.CHIP_PLACE_CODE
WHERE AB.NAME = 'Lucy';

-- 3. Kuris šeimininkas augina daugiausiai gyvūnų? Pateikti šeiminiko vardą ir pavardę.
SELECT COUNT(A.HOST_ID) AS 'ANIMAL_NUMBER', H.NAME, H.SURNAME
FROM ANIMAL A
JOIN HOST H ON A.HOST_ID = H.HOST_ID
GROUP BY A.HOST_ID
ORDER BY ANIMAL_NUMBER DESC
LIMIT 1;

-- 4. Papildyti šeimininkui ID 577154 adresą 7524 Jackson St. 
SET SQL_SAFE_UPDATES = 0;

UPDATE HOST
SET ADDRESS = '7524 Jackson St.'
WHERE HOST_ID = 577154;

SELECT *
FROM HOST 
WHERE HOST_ID = 577154; 

-- 5. Atnaujinti gyvūno Ivy lyties kodą į 5. 
UPDATE ANIMAL_BASIC
SET GENDER_ID = 5
WHERE NAME = 'IVY';

SELECT *
FROM ANIMAL_BASIC 
WHERE NAME = 'IVY';

-- 6. Ištrinti šeiminiko ID = 004689 duomenis iš visų lentelių. 
DELETE FROM ANIMAL 
WHERE HOST_ID = 004689;

DELETE FROM ANIMAL_BASIC 
WHERE HOST_ID = 004689;

DELETE FROM HOST
WHERE HOST_ID = 004689;

-- 7. Įterpti naują gyvūno spalvą į lentelę "Colour". Colour_code = 13, Name = Brown, Fur_Type = Short haired
INSERT INTO COLOUR
VALUES (13, 'Brown', 'Short haired');

SELECT *
FROM COLOUR;

-- 8. Kokių gyvūnų rūšių yra daugiausia?
SELECT COUNT(CATEGORY) AS 'NUMBER', CATEGORY 
FROM SPECIES
GROUP BY CATEGORY 
ORDER BY NUMBER DESC;

-- 9. Kokius gyvūnus augina Ruben Barnes? Pateikti gyvūnų vardus, rūšis, kategorijas, spalvas, lytis, kastraciją.
SELECT AB.NAME AS 'NAME', S.NAME AS 'SPECIES', S.CATEGORY AS 'CATEGORY', C.NAME AS 'COLOUR', G.NAME AS 'GENDER', G.CASTRATION AS 'CASTRATION'
FROM ANIMAL_BASIC AB
JOIN SPECIES S ON AB.SPECIES = S.SPECIES_CODE
JOIN COLOUR C ON S.COLOUR_CODE = C.COLOUR_CODE
JOIN GENDER G ON AB.GENDER_ID = G.GENDER_ID 
JOIN HOST H ON AB.HOST_ID = H.HOST_ID
WHERE H.NAME = 'RUBEN'
AND H.SURNAME = 'BARNES';

-- 10. Kurioje vietoje čipų yra daugiausia?
SELECT COUNT(C.CHIP_PLACE_CODE), CH.NAME
FROM CHIP C
JOIN CHIP_PLACE CH ON C.CHIP_PLACE_CODE = CH.CHIP_PLACE_CODE
GROUP BY CH.NAME;
